[project]
name = "dbt-exasol"
version = "1.9"
description = "Adapter to dbt-core for warehouse Exasol"
authors = [
  { name = "Torsten Glunde", email = "torsten.glunde@alligator-company.com" },
  { name = "Ilija Kutle", email = "ilija.kutle@alligator-company.com" },
]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "pyexasol>1.0,<1.4",
    "dbt-adapters>=1.10.0",
    "pip-audit>=2.9.0",
]

[dependency-groups]
dev = [
  "bandit>=1.9.2",
  "dbt-tests-adapter>=1.19.4",
  "hologram>=0.0.16",
  "pytest>=8.4.2",
  "pytest-asyncio>=1.3.0",
  "pytest-cov>=7.0.0",
  "pytest-watch>=4.2.0",
  "pytest-xdist>=3.8.0",
  "python-dotenv>=1.2.1",
  "ruff>=0.14.7",
]

[build-system]
requires = ["uv-build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "dbt"

[tool.pytest]
addopts = ["-n4"]
